# Generated by Django 5.1.7 on 2025-03-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productforcart'),
        ('user_auth', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='shopping_cart',
            field=models.ManyToManyField(blank=True, related_name='users_in_cart', to='shop.productforcart'),
        ),
    ]
