# Generated by Django 5.1.7 on 2025-06-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_remove_customuser_shopping_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='access',
            field=models.CharField(choices=[('user', 'User'), ('CM', 'ContentManager'), ('OM', 'OrderManager'), ('AD', 'Admin')], default='user', max_length=10),
        ),
    ]
