# Generated by Django 5.1.7 on 2025-06-25 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0008_remove_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInforamtion',
            new_name='UserInformation',
        ),
    ]
