# Generated by Django 5.1.7 on 2025-06-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_productforcart_user_alter_cart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='productforcart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
