# Generated by Django 5.1.7 on 2025-06-09 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_review_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productforcart',
            name='user',
        ),
        migrations.AddField(
            model_name='productforcart',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.cart'),
            preserve_default=False,
        ),
    ]
