# Generated by Django 5.1.7 on 2025-06-09 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_productforcart_user_productforcart_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productforcart',
            name='cart',
        ),
    ]
